"""New migeration

Revision ID: db2856bc5188
Revises: 
Create Date: 2025-07-02 15:40:08.571610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db2856bc5188'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_create_at'), table_name='author')
    op.drop_index(op.f('ix_author_deleted_at'), table_name='author')
    op.drop_index(op.f('ix_author_deleted_by'), table_name='author')
    op.drop_index(op.f('ix_author_updated_at'), table_name='author')
    op.alter_column('books', 'published_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_index(op.f('ix_books_create_at'), table_name='books')
    op.drop_index(op.f('ix_books_deleted_at'), table_name='books')
    op.drop_index(op.f('ix_books_deleted_by'), table_name='books')
    op.drop_index(op.f('ix_books_updated_at'), table_name='books')
    op.drop_index(op.f('ix_borrower_create_at'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_deleted_at'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_deleted_by'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_updated_at'), table_name='borrower')
    op.create_foreign_key(None, 'borrower', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrower', type_='foreignkey')
    op.create_index(op.f('ix_borrower_updated_at'), 'borrower', ['updated_at'], unique=False)
    op.create_index(op.f('ix_borrower_deleted_by'), 'borrower', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_borrower_deleted_at'), 'borrower', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_borrower_create_at'), 'borrower', ['create_at'], unique=False)
    op.create_index(op.f('ix_books_updated_at'), 'books', ['updated_at'], unique=False)
    op.create_index(op.f('ix_books_deleted_by'), 'books', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_books_deleted_at'), 'books', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_books_create_at'), 'books', ['create_at'], unique=False)
    op.alter_column('books', 'published_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('ix_author_updated_at'), 'author', ['updated_at'], unique=False)
    op.create_index(op.f('ix_author_deleted_by'), 'author', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_author_deleted_at'), 'author', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_author_create_at'), 'author', ['create_at'], unique=False)
    # ### end Alembic commands ###
